export enum ProcessStatus {
  PROCESS_DESIGN = "PROCESS_DESIGN",
  MODEL_DESIGN = "MODEL_DESIGN",
  FORM_DESIGN = "FORM_DESIGN",
  ROLE_DESIGN = "ROLE_DESIGN",
  PERFORMERS = "PERFORMERS",
  RUNNING = "RUNNING",
  STOP = "STOP",
}
